var annotated_dup =
[
    [ "CHome", "class_c_home.html", "class_c_home" ],
    [ "Config_File", "class_config___file.html", "class_config___file" ],
    [ "CRegistrazione", "class_c_registrazione.html", "class_c_registrazione" ],
    [ "CRicerca", "class_c_ricerca.html", "class_c_ricerca" ],
    [ "CUpload", "class_c_upload.html", "class_c_upload" ],
    [ "CUtente", "class_c_utente.html", "class_c_utente" ],
    [ "EAvventura", "class_e_avventura.html", "class_e_avventura" ],
    [ "ECommento", "class_e_commento.html", "class_e_commento" ],
    [ "EUtente", "class_e_utente.html", "class_e_utente" ],
    [ "FAvventura", "class_f_avventura.html", "class_f_avventura" ],
    [ "FCommento", "class_f_commento.html", "class_f_commento" ],
    [ "Fdb", "class_fdb.html", "class_fdb" ],
    [ "FUtente", "class_f_utente.html", "class_f_utente" ],
    [ "Smarty", "class_smarty.html", "class_smarty" ],
    [ "Smarty_Compiler", "class_smarty___compiler.html", "class_smarty___compiler" ],
    [ "USession", "class_u_session.html", "class_u_session" ],
    [ "USingleton", "class_u_singleton.html", null ],
    [ "VHome", "class_v_home.html", "class_v_home" ],
    [ "View", "class_view.html", "class_view" ],
    [ "VRegistrazione", "class_v_registrazione.html", "class_v_registrazione" ],
    [ "VRicerca", "class_v_ricerca.html", "class_v_ricerca" ],
    [ "VUpload", "class_v_upload.html", "class_v_upload" ],
    [ "VUtente", "class_v_utente.html", "class_v_utente" ]
];